package br.com.cvc.core.enums;

public enum LogTypeEnum {
    CALL_SENT_TO_ORCHESTRATOR,
    ORC_SPRINGBOOT_CORP_AUTH_LOGIN,
    FIND_ALL_BRANCHES,
    FIND_ALL_CITIES_BY_COUNTRY_ID_AND_STATE_ID,
    FIND_ALL_COUNTRIES,
    FIND_ALL_OPERATIONS,
    FIND_ALL_PACKAGE_GROUPS,
    FIND_ALL_PRODUCTS,
    FIND_ALL_STATES_BY_COUNTRY_ID,
    FIND_ALL_SUPPLIERS_BY_PARAMS,
    FIND_ALL_SYSTEMS
}
